In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

df = pd.read_csv("BostonHousing.csv")

df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [2]:
df = df.dropna()

In [3]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
df.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [7]:
x = df[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b']]

In [8]:
x.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90

In [13]:
y = df["medv"]

In [14]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: medv, dtype: float64

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 42)
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [17]:
y_pred = model.predict(x_test)

In [18]:
y_pred

array([ 1.01310825, 23.2876788 , 13.11610239, 28.95439783, 22.58216573,
       15.69414526, 15.27880997, 19.94918991, 22.52014974, 11.34980571,
       20.59636791, 30.7291257 ,  4.09771144, 24.74300412,  8.96056788,
       10.39388376, 23.33503418, 16.92111312, 23.45937749, -1.90138011,
       16.65652109, 19.21149079, 28.17086826, 17.75328615, 21.97759626,
       18.99121348, 25.40474382, 27.94166856, 19.05287062, 20.51728523,
       15.38374343, 31.06797393, 18.13648187, 30.55861389, 29.6949693 ,
       21.32099566, 13.72569945, 24.81083037, 20.6426536 , 25.23379266,
       14.79384727, 36.90048976, 15.71836158, 31.49969415, 15.73393675,
       28.02512666, 27.96851021, 23.52950705, 16.67528258, 15.71280363,
       24.06569202, 33.73302079, 16.51697697, 17.3959082 , 36.35635537,
       31.36194754, 15.24616924, 16.84688747, 20.34112806, 25.77351737,
       20.90176765, 43.88848288, 21.99157862, 11.51226511, 25.35396365,
       28.87953002, 10.46700242, 16.18079599, 27.03729097, 16.7657773 ,
       22.59367893, 15.73591025, 41.15724774, 28.72267585, 21.20747143,
       21.73179653, 38.13975993, 23.82266063, 20.08261888, 20.25103034,
       21.84486272, 27.00008741, 19.72209134, 26.59541914, 22.82765253,
       27.58722764, 25.42525458, 18.45108942, 19.40951134, 47.18474023,
       10.14152628, 19.86489194, 16.97478404, 25.21835051, 10.74936188,
       16.56412236, 30.57302511, 22.67585353, 13.02609794, 18.72991762,
       22.76167817, 18.62531526, 14.33700214, 20.75147826, 18.16234859,
       20.54728224, 35.40435072, 31.84411393, 19.13546746, 20.0109514 ,
       19.1795169 , 15.25294806, 19.86112437, 15.04189341, 20.8982688 ,
       22.00842198, 25.31478766, 24.90554499, 21.78451213, 22.9001327 ,
       41.88779559, 26.77817616, 24.14932558, 24.17671007, 30.53821049,
       38.43783061])

In [19]:
model.score(x_train, y_train)

0.6591267675583008

In [20]:
model.score(x_test, y_test)

0.7661278405740807

In [21]:
np.sqrt(mean_squared_error(y_test, y_pred))

np.float64(4.209372111886099)